<a href="https://colab.research.google.com/github/joannnnnnnnnnn24/activities/blob/main/bakery_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Despogado, Joan

In [2]:
import numpy as np

In [1]:
quantity_sold=[17,40,1]
type(quantity_sold)

list

In [4]:
price=[2,1,10]
type(price)

list

In [5]:
price_array=np.array(price)
quantity_sold_array=np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [6]:
price_array* quantity_sold_array

array([34, 40, 10])

In [9]:
price_array=price_array+[7]
print(price_array)

[ 9  8 17]


In [10]:
price_array=price_array-[7]

price_array=np.append(price_array,7)
print(price_array)

[ 2  1 10  7]


In [11]:
price * quantity_sold_array

array([34, 40, 10])